spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: registration-service
          uri: http://localhost:8081
          predicates:
            - Path=/movie-app/**           
        - id: authentication-service
          uri: http://localhost:8082
          predicates:
            - Path=/movie-app/user/**            
        - id: movie-service
          uri: http://localhost:8083
          predicates:
            - Path=/movie/**
          # filters:
          #   - name: AuthenticationFilter1            
        - id: wishlist-service
          uri: http://localhost:8084
          predicates:
            - Path=/movies/wishlist/**
          # filters:
          #   - name: AuthenticationFilter1  
server:
  port: 8085
